# Boost
MINGW_BOOST_DIR = /c/Boost

MINGW_BOOST_INCLUDE_DIR = $(MINGW_BOOST_DIR)/include/boost-1_57
MINGW_BOOST_LIB_DIR = $(MINGW_BOOST_DIR)/lib
MINGW_BOOST_LIB_EXT = -mgw48-mt-d-1_57

# mman-win32
MINGW_MMAN_DIR = ../mman-win32

MINGW_MMAN_INCLUDE_DIR = $(MINGW_MMAN_DIR)
MINGW_MMAN_LIB_DIR = $(MINGW_MMAN_DIR)

# graphviz
MINGW_GRAPHVIZ_DIR = /c/Program\ Files/Graphviz2.38

MINGW_GRAPHVIZ_INCLUDE_DIR = $(MINGW_GRAPHVIZ_DIR)/include
MINGW_GRAPHVIZ_LIB_DIR = $(MINGW_GRAPHVIZ_DIR)/lib/release/dll

# Codesynthesis XSD
#MINGW_XSD_DIR = /c/Program\ Files/CodeSynthesis\ XSD\ 4.0
#MINGW_XSD_INCLUDE_DIR = $(MINGW_XSD_DIR)/include
MINGW_XSD_DIR = /c/ICF_AutoCapsule_disabled/xsd-4.0.0-i686-windows
MINGW_XSD_INCLUDE_DIR = $(MINGW_XSD_DIR)/libxsd
MINGW_XSD_COMMAND = $(MINGW_XSD_DIR)/bin/xsd
