/*
 * generated by AddMeasurement
 *
 * DO NOT CHANGE THIS FILE
 */

#ifndef MEASURE_H
#define MEASURE_H

/* Block IDs */
#define FIBONACCI_ABS 0
#define FIBONACCI_ADD 1
#define FIBONACCI_DIVIDE 2
#define FIBONACCI_FN 3
#define FIBONACCI_FN_1 4
#define FIBONACCI_GAIN 5
#define FIBONACCI_GOLDEN_RATIO 6
#define FIBONACCI_SATURATION 7
#define FIBONACCI_SUBTRACT 8

/* Maximum Block ID */
#define MAX_BLOCK_ID 9

/* Block Parameters */
#ifndef FIBONACCI_ABS_PARAM
#define FIBONACCI_ABS_PARAM	0
#endif
#ifndef FIBONACCI_ADD_PARAM
#define FIBONACCI_ADD_PARAM	0
#endif
#ifndef FIBONACCI_DIVIDE_PARAM
#define FIBONACCI_DIVIDE_PARAM	0
#endif
#ifndef FIBONACCI_FN_PARAM
#define FIBONACCI_FN_PARAM	0
#endif
#ifndef FIBONACCI_FN_1_PARAM
#define FIBONACCI_FN_1_PARAM	0
#endif
#ifndef FIBONACCI_GAIN_PARAM
#define FIBONACCI_GAIN_PARAM	0
#endif
#ifndef FIBONACCI_GOLDEN_RATIO_PARAM
#define FIBONACCI_GOLDEN_RATIO_PARAM	0
#endif
#ifndef FIBONACCI_SATURATION_PARAM
#define FIBONACCI_SATURATION_PARAM	0
#endif
#ifndef FIBONACCI_SUBTRACT_PARAM
#define FIBONACCI_SUBTRACT_PARAM	0
#endif

/*
 * Block Names
 */
const char *BLOCK_NAMES[] = {
	"Fibonacci_Abs",
	"Fibonacci_Add",
	"Fibonacci_Divide",
	"Fibonacci_Fn",
	"Fibonacci_Fn_1",
	"Fibonacci_Gain",
	"Fibonacci_Golden_ratio",
	"Fibonacci_Saturation",
	"Fibonacci_Subtract",
};

#define MEASUREMENT_STEP_FUNCTION	Fibonacci_step
#define MEASUREMENT_INITIALIZE_FUNCTION	Fibonacci_initialize

#endif
